ExUnit.start()
Code.require_file("support/story_world_fixture.ex", __DIR__)
Code.require_file("support/phase_four_fixture.ex", __DIR__)
Code.require_file("support/phase_six_fixture.ex", __DIR__)
Code.require_file("support/phase_seven_fixture.ex", __DIR__)
Code.require_file("support/phase_eight_fixture.ex", __DIR__)
